# dataset root directory, acts as a 'root' for the train and val
path: /home/ben/projects/spaceInvaders64AI/data
  
# training data
train: images

# data for evaluation, for now just uses the same as the training
val: images

# the string rep. of each index
names:
  0: red_alien
  1: blue_alien
  2: green_alien
  3: yellow_alien
  4: red_bullet
  5: yellow_bullet
  6: green_bullet
  7: blue_bullet
  8: mothership
  9: player
  10: barrier